# -*- mode: ruby -*-
# vi: set ft=ruby  :

machines = {
  "node1" => {"memory" => "4096", "cpu" => "4", "ip" => "192.168.56.10", "image" => "generic/ubuntu1804"},
  "node2" => {"memory" => "2048", "cpu" => "2", "ip" => "192.168.56.20", "image" => "generic/ubuntu1804"},
  "node3" => {"memory" => "2048", "cpu" => "2", "ip" => "192.168.56.30", "image" => "generic/ubuntu1804"}
}
  
Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.boot_timeout = 600
  machines.each do |name, conf|
    config.vm.define "#{name}" do |machine|
      machine.vm.box = "#{conf["image"]}"
      machine.vm.hostname = "#{name}.lab"
      machine.vm.network "private_network", ip: "#{conf["ip"]}"
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
        vb.customize ["modifyvm", :id, "--groups", "/CK"]
      end
        if "#{conf["image"]}" == "generic/ubuntu1804" or "#{conf["image"]}" == "debian/buster64"
          machine.vm.provision "shell", inline: "apt-get update; apt-get install python -y; apt-get install language-pack-pt; locale-gen pt_BR.UTF-8; hostnamectl set-hostname #{name}.lab"
        end
        if "#{conf["image"]}" == "centos/7"
          machine.vm.provision "shell", inline: "yum update ; yum install net-tools -y; hostnamectl set-hostname #{name}.lab"
        end
    end
  end
  config.vm.provision "shell", path: "script.sh"
end
